name: Deploy to AWS CodeDeploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select a feature branch to deploy"
        required: true
        default: "feat/monitoring-agent-setup"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug AWS_REGION
        run: echo ${{ vars.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to AWS CodeDeploy
        id: deploy
        run: |
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name ${{ vars.CODEDEPLOY_APPLICATION }} \
            --deployment-group-name ${{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --description "GitHub Actions deployment from commit ${{ github.sha }}" \
            --query "deploymentId" --output text)

          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV

      - name: Wait for deployment to complete
        run: |
          STATUS="InProgress"
          while [[ "$STATUS" == "InProgress" || "$STATUS" == "Created" ]]; do
            sleep 10
            STATUS=$(aws deploy get-deployment \
              --deployment-id $DEPLOYMENT_ID \
              --query "deploymentInfo.status" --output text)
            echo "Current Deployment Status: $STATUS"
          done

          if [[ "$STATUS" != "Succeeded" ]]; then
            echo "Deployment failed with status: $STATUS"
            exit 1
          fi

          echo "Deployment succeeded!"
